CREATE DATABASE dbteste;

USE dbteste;

CREATE TABLE genero (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(10) NOT NULL
) ENGINE = innodb;

CREATE TABLE cliente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    telefone BIGINT(14),
    email VARCHAR(100) NOT NULL,
    dataNascimento DATE,
    generoId INT,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (generoId) 
    REFERENCES genero (id) ON DELETE RESTRICT
) ENGINE = innodb;

CREATE TABLE produto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(45) NOT NULL,
    valor DOUBLE(10,2) UNSIGNED NOT NULL
) ENGINE = innodb;

CREATE TABLE situacao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(15) NOT NULL
) ENGINE = innodb;

CREATE TABLE pedido (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dataPedido DATE NOT NULL,
    totalItens INT UNSIGNED,
    valorTotal DOUBLE(10,2) UNSIGNED,
    situacaoId INT NOT NULL,
    clienteId INT NOT NULL,
    CONSTRAINT FK_PEDIDO_SITUACAO FOREIGN KEY (situacaoId) 
    REFERENCES situacao (id) ON DELETE RESTRICT,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (clienteId) 
    REFERENCES cliente (id) ON DELETE RESTRICT
) ENGINE = innodb;

CREATE TABLE itemPedido (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pedidoId INT NOT NULL,
    produtoId INT NOT NULL,
    quantidadeProduto INT UNSIGNED,
    valor DOUBLE(10,2) UNSIGNED,
    valorTotal DOUBLE(10,2) UNSIGNED,
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (pedidoId) 
    REFERENCES pedido (id) ON DELETE RESTRICT,
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (produtoId) 
    REFERENCES produto (id) ON DELETE RESTRICT
) ENGINE = innodb;
